### ISSUE TITLE
which characters, exactly, should be removed in the matching algorithm?

### ISSUE THREAD

**Issue by aphillips** [w3c/charmod-norm#117]
In the latest version of the matching algorithm, I noticed that the advice is to "remove Unicode controls", but this was non-specific and linked to the section on invisibles. I created the following list and also had a question about whether this was complete or correct:

> Issue 1
> 
> What to do about non-breaking space and other space characters? Is this the full list? What about the 
> Mongolian characters?
> Remove all of the following invisible Unicode characters:
>
>    ZWJ, ZWNJ
>    Variation Selectors (FE00..FE0F)
>    COMBINING GRAPHEME JOINER 034F
>    SOFT HYPHEN 00AD
>    ZERO WIDTH SPACE 200B
>    Bidi controls

**Comment by asmusf** [comment]
The text in that section states about ZWJ/ZWNJ " Their original use was to control ligature formation—either preventing the formation of undesirable ligatures or encouraging the formation of desirable ones."
This is not in accordance with the history. They got **_started_** as "join controls" for Arabic, where, for example in Persian, they are needed to control joining that affects the way a word is read (meaning).
They were later generalized to allow breaking (ZWNJ) or requesting (ZWJ) ligatures and also to affect conjunct formation in Indic scripts.

**Comment by asmusf** [comment]
The section states "In almost all of these cases, users may not be aware of or cannot be sure if a given document or text string has included or omitted one of these characters."

This is actually only partially true. While users may not be aware of the presence of these characters, when they do affect the layout of a word, that difference is certainly visible to a user.

That's why in IDNA 2008 there are context rules for ZWJ / ZWNJ that attempt to distinguish cases where the joiners have no effect (or only optional effect) and where they do. For example, adding a non-joiner where two characters would have joined makes a clear visual difference; doing the same thing between two characters that wouldn't have joined anyway remains undetectable.

The rules treat the conjunct formation also as making these characters effect visible; that is, their presence is allowed in those locations in an IDNA2008 identifier (which makes them meaningful for matching).

SHY is an example of a character which is always invisible _*except*_ when it causes the word to break across a line. There's a much stronger case for filtering it unconditionally in matching.

Variation selectors are more akin to font selection; if no suitable glyphs exist, they have no visible effect. Removal seems fine.

ZWSP and WJ (the replacement for ZWNBSP, aka BOM) are like SHY, they have no visible effects except in line breaking or segmentation. Removal seems fine.

And so on.
ZWJ for conjunc

**Comment by aphillips** [comment]
We've removed all of this guidance, leaving behind a section on "Additional Match Tailoring". Everyone satisfied?

> Some implementations might require additional tailoring to assist with matching. This might include removing certain Unicode controls or invisbile markers, mapping together or removing characters that are part of the syntax, or performing a whitespace trim.

> Specificiations need to clearly define any additional tailoring done as part of the matching process. Care should be taken not to interfere with the encoding of different languages. For example, a process that removes all combining characters based on Unicode character classes will not support languages that rely on combining marks and lead to user frustration. An example of this would be the various Indic scripts which use combining marks to encode or suppress vowels.

**Comment by r12a** [comment]
> Variation selectors are more akin to font selection; if no suitable glyphs exist, they have no visible effect. Removal seems fine. 

I don't think that's the case for Mongolian, where they produce expected visual changes in the same way as ZWNJ does for Persian. Until we start using a graphetic approach for Mongolian, i think it would be problematic to eliminate VSs.

Anyway, i think that's moot, given the current text.
