### ISSUE TITLE
Various Editorial Suggestions

### ISSUE THREAD

**Issue by stpeter** [w3c/charmod-norm#154]
Overall the document looks very good. Here are some relatively small editorial suggestions (take them or leave them as desired)...

1. https://w3c.github.io/charmod-norm/#goals

I suggest changing "and" to "or" here to be more inclusive (because any one of these factors could be significant): "regardless of their language, script, writing system, and cultural conventions"

2. https://w3c.github.io/charmod-norm/#terminology

The phrasing here is slightly loose: "Some characters that are used in the various examples might not appear as intended unless you have the appropriate font." I suggest "... unless the visual display device you are using supports a font from the appropriate font family." (or "font face")

Example 2 uses the term "character" twice but then talks about "code points"; is consistency desirable here (or should we make it explicit that both terms refer to the same thing)?

3. https://w3c.github.io/charmod-norm/#definitionCaseFolding

Example 6: "it's" should be "its"

4. https://w3c.github.io/charmod-norm/#caseMappingLanguageSensitivity

Example 8: "even thought" -> "even though"

5. https://w3c.github.io/charmod-norm/#caseFoldApplication

It might be good to provide a citation for the ASCII subset of Unicode.

6. https://w3c.github.io/charmod-norm/#unicodeNormalization

Here we use the term "logical character" but later on (e.g., in https://w3c.github.io/charmod-norm/#canonical_compatibility) we use the term "abstract character"; perhaps it makes sense to harmonize?

7. https://w3c.github.io/charmod-norm/#canonical_compatibility

In Example 11, it might be helpful to include the Unicode code points.

8. https://w3c.github.io/charmod-norm/#composition_decomposition

"a given base character and combining mark are not replaced" -> "a given base character and combining mark is not replaced"

9. https://w3c.github.io/charmod-norm/#legacyCharacterEncoding

"existance" -> "existence"

10. https://w3c.github.io/charmod-norm/#sec_case_sensitive

"Vocabularies usually puts" - the last word should be "put"

Also: "Case insensitivity is usually be reserved" (strike "be")

11. https://w3c.github.io/charmod-norm/#sec_language_tailoring

In several places here, the term "language-sensitive" is used but I think we mean "language-specific" (in any case, it would be good to be consistent). Similarly for "locale-sensitive".

12. https://w3c.github.io/charmod-norm/#additionalMatchTailoring

There is a missing close paren in the second paragraph.

**Comment by aphillips** [comment]
1: Done
2: This is a good suggestion, but I thought the wording ended up a bit strange. I applied a deeper edit:

>  Some characters used in this document's examples might not appear as intended on your specific device or display. Usually this is due to lack of a script-specific font installed locally or due to other limitations of your specific rendering system. This document uses a Webfont to provide fallback glyphs for many of the non-Latin characters, but your device might not support displaying the font. To the degree possible, the editors have tried to ensure that the examples nevertheless remain understandable.

I noticed (actually, it's been burning in my mind for a while) that we don't define "code point" any where, even though we use the term liberally. I added a definition of code point:

> A <dfn data-lt="Unicode code point|code point|code points">Unicode code point</dfn> (or "code point") refers to the numeric value assigned to each Unicode character. Unicode code points range from 0 to 0x10FFFF<sub>16</sub>. (See Section 4.1 in [[!CHARMOD]] for a deeper discussion of character encoding terminology.)

3. Ugh. Done.

4. Done.

5. Amusingly, ASCII and ISO/IEC 646 aren't in Specref. I don't really want to reference RFC20. I copied in the ref from Charmod. As part of this, I notice that specref no longer supports the `note` feature, which we used in some of our references. I will follow up on that separately.

6. I replaced the two occurrences of "logical character" with "abstract character" (and some rewriting in both places).

7. Agreed. I didn't do that work yet and will create a separate issue for the necessary PR.

8. Done.

9. Done.

10. A wildebeest puts... never mind... Done (the wildebeest reference will have to be explained in teleconference)

11. Done.

12. Fixed. I converted the parenthetical to a separate sentence (An example of this...) since the sentence is followed by a parenthetical sentence.

Thank you for the review!!
