### ISSUE TITLE
ASCII case folding undefined

### ISSUE THREAD

**Issue by svgeesus** [w3c/charmod-norm#209]
In [3.1 Specifying Content Restrictions](https://w3c.github.io/charmod-norm/#specifying-content-restrictions)

> ASCII case folding is RECOMMENDED.

Agreed, but that seems to be the sole use of the term.

I feel it would be helpful to define it. For example does it apply only to ASCII strings, or to the ASCII codepoints in Unicode strings. How it is different from locale-specific folding (I maps to i not ı, etc)

In CSS we link to [this definition](https://infra.spec.whatwg.org/#ascii-case-insensitive) so I suggest that this document do the same.

**Comment by aphillips** [comment]
Thanks for noticing the missing link :-)

We do have a definition in the document itself, in [section 3.2.2.2](https://w3c.github.io/charmod-norm/#ASCIIFoldNormalizationStep) which is (intentionally) identical to the one in the Infra spec. Since Infra itself is widely used, I think it makes sense to include a pointer, keeping the local definition as informative.

**Comment by svgeesus** [comment]
That sounds like a good outcome to me.

Having a duplication does require tracking the upstream definition in case it changes.

**Comment by aphillips** [comment]
Upon further reflection, I decided to switch to using the definition in INFRA explicitly, fixing the links and tweaking along the way. In this case, I'm not worried about the definition in Infra (or elsewhere) changing, since the ASCII case fold has been stable "for a while now" ;-)
