### ISSUE TITLE
Does ZWJ/ZWNJ affect meaning?

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#44]
section 2.4 of the document[1] says

> A special case are the Unicode control characters U+200D Zero Width Joiner (also known as ZWJ) and U+200C Zero Width Non-Joiner (also known as ZWNJ). These invisible controls sometimes do affect the meaning of characters sequences where they appear, although their usual use is to control ligature formation— either preventing the formation of undesirable ligatures or encouraging the formation for desirable ones.

is this correct, ie. that the presence of ZWJ or ZWNJ can actually change the meaning of the text. If so, do we have an example?

[1] http://w3c.github.io/charmod-norm/#unicodeControls

**Comment by duerst** [comment]
I don't have an actual example with a minimal pair, but I guess there should be examples of minimal pairs in Persian. Even if we cannot find a minimal pair, my understanding is that the ZWNJ is used to separate very specific endings in Persian, and leaving it out wouldn't just be a "less desirable" way of connecting the characters, but it would be considered as a straightforward orthographic error.

So your current wording, "while they are not semantically part of the text", definitely looks doubtful/inappropriate to me. As this sentense intents to show, there are many minour changes that one can make to a tekst without really afecting its semantiks.

Also, I think there are minimal pairs in German, where the presence or absence of a ligature, at least in print quality text, indicates how a composite noun is broken into noun parts. This isn't strictly orthographic, as it isn't used with typewriters, email, and so on, but it's definitely semantically relevant. For actual examples, I'd suggest to search in the unicode/unicode archives for emails from Asmus, or contact him directly.

**Comment by johnwcowan** [comment]
Indeed, the first example at https://en.wikipedia.org/wiki/Zero-width_non-joiner
 shows that the Persian for "I want to" becomes downright illegible when spelled without ZWNJ.

**Comment by Ladsgroup** [comment]
As a native Persian speaker I was asked to comment on this:
*In some words using ZWNJ in incorrect place make the context illegible and meaningless like "همیشه" ("always") when it becomes "همی‌شه" (nonsense)
*Not using ZWNJ in places we should sometimes keeps the meaning but highly discouraged like "میروم" ("I'm going") which the correct way is "می‌روم" but a native speaker can see they are not different in meaning
but sometime not using it make the work ineligible like "بهرهوری" (nonsense) which in this case it must be "بهره‌وری" ("efficiency") in these cases when ZWNJ is not available (like old keyboard layouts) people use full space "بهره وری" and it's obviously highly discouraged but a native speaker can see they are not different.

**Comment by aphillips** [comment]
@Ladsgroup Thanks for the comment. I'm not quite clear on the example at the end. Does the comment:

> make the work ineligible like "بهرهوری" (nonsense)

... mean that the text literally makes no sense without ZWNJ?

Reading this thread today, I'm thinking: should I be getting rid of the whole "affects the semantics" idea here? It seems tricky to define the boundary between whether a character's effect is "semantic" or not. Instead of saying:

> Unicode provides a number of special purpose control characters and other invisible markers that 
> help document authors control the appearance or performance of text. In poorly implemented 
> applications, these characters can interfere with string matching because, while they are not 
> semantically part of the text, they do form part of the encoded character sequence. 

I might instead say:

> Unicode provides a number of special purpose control characters and other invisible markers that 
> help document authors control the appearance or performance of text. Because these characters
> are invisible, users are not always aware of their presence or absence. As a result, these
> characters can interfere with string matching when they are part of the encoded character 
> sequence but the expected matching text does not include them.

We can then go on to eliminate the "ZW[N]J special case" discussion and just talk about each type of invisible control (what it is used for, etc.)

**Comment by ebraminio** [comment]
While this is not a very common example but probably shows essence of ZWNJs in order to not consider just clearing them out: تن‌ها and تنها, the only difference is on the fact the first one has a ZWNJ in the middle; while the first is a noun and plural form of "تن" and means "bodies" or "corpuses", the second one is an adjective and means "alone" thus semantically unrelated. So your main question's answer is yes, it affects the meaning and shouldn't be just removed however the same couldn't be said about ZWJ which is rarely used on the normal and formal Persian text and perhaps its removal won't harm much wherever it used, however I can't assure you that the same would be true on other scripts or even other Arabic script variants.

**Comment by johnwcowan** [comment]
I think a plausible analogy would be English handwritten text that has been squeezed into too small a space so that the letters overlap one another.  You can decipher it, but it's hard, and at first sight it looks like a meaningless scribble, or worse yet like some other word altogether.

**Comment by behdad** [comment]
> make the work ineligible like "بهرهوری" (nonsense)
> 
> ... mean that the text literally makes no sense without ZWNJ?

Yes.  It will be pronounced completely differently, and makes no sense.

> is this correct, ie. that the presence of ZWJ or ZWNJ can actually change the meaning of the text. If so, do we have an example?

Totally. For example, removing the ZWNJ in all of the following (and countless other Persian words) will make them illegible:
خانه‌ها
خامنه‌ای

> ...although their usual use is to control ligature formation— either preventing the formation of undesirable ligatures or encouraging the formation for desirable ones."

I'd go as far as suggesting that their ligature control function is rather unused and discouraged.  Their main function in Unicode, these days, is to control shaping for Arabic-like and Indic-like scripts.

**Comment by behdad** [comment]
A few other examples where removing the ZWNJ changes or to a different word with completely different meaning:

بازه‌ای
سازه‌ای
خانه‌ای
جامه‌ای
...

**Comment by aphillips** [comment]
Thanks to everyone on this thread for their contributions. I have updated section 2.4 in my copy (which I will merge shortly).

@ebraminio I used your example of alone/corpuses in the text. (If you wish to be acknowledged using a name other than you screenname, please let me know)

Please review my changed text. Suggestions and further comment very much welcome!

**Comment by ebraminio** [comment]
Oh, thank you! I've just updated my profile with my full name and an email if is needed :)

**Comment by r12a** [comment]
I'm not sure we're finished with this section yet.  We note that matching can fail if these characters are hanging around, but we don't say what the implications of that are for implementers.  (I don't think we mean to say that content authors shouldn't use them.)

I think the question that needs answering is whether the implementers should ignore the invisible characters while matching strings, or not.  The answer is apparently not clear cut.  

[1] In most cases it seems that they should be ignored – including Persian cases such as بهرهوری vs بهره‌وری, where it makes a difference to the reader but not to the machine that is doing the comparison.

[2] However, there appear to be some specific instances in certain locales where certain characters do make a semantic difference, such as where they create the distinction in meaning between تنها ("alone") and the word تن‌ها  ("bodies" or "corpuses") in Persian.  If the matching algorithm needs to be sensitive to semantic differences of this kind, then the implementation needs to take the invisible characters used in those particular circumstances into account.  By implication, it therefore needs to know how to identify those circumstances.

[3] We should also note that good matching algorithms may have to contend with workarounds that people apply, such as the example mentioned by @Ladsgroup with بهره وری. In this case, the matching algorithm needs to be aware that some people use spaces instead of zwnj, so in such cases the space should be ignored when matching.  (Similar issues may arise in nastaliq script, where spaces may or may not be used as word separators, as i understand.) (And by the way we haven't touched on morphological reduction for matching, which is particularly difficult in arabic, but also complicated by agglutinative languages – but that's another story.)

By the way, i suspect that similar things could be said about invisible characters in Mongolian. I think that the FVS characters change the visual appearance rather than the meaning, whereas the MVS character (also invisible, and also producing an effect on the glyph rendering) also indicates a suffix boundary that may be semantically significant. We could ask on the mongolian list.

**Comment by aphillips** [comment]
Generally for matching a lot of these characters are probably ignorable, although it depends on the context.

If the context is the "find" portion of Charmod, then I think the recommendation is to ignore them always. If you're searching for "alone" and run into some "bodies" along the way, that may not be so bad. Similarly the various Variation Selectors (Mongolian Free or just plain old VSx) probably should be excluded.

If the context were to be namespaced matching operations, I'm not as clear on it. In fact, I suspect that this is kind of the same problem that normalization is. If normalization is not specified or externally supplied by the specification (that is, it isn't done when matching), then it is up to the document author(s) to ensure that they use the same character sequences. Then your "bodies" are never "alone" :-). The advice, instead, is to avoid using invisibles in IDs, names, attributes, etc. unless it cannot be avoided. And then, if the characters are required, to adopt a consistent encoding of the text to avoid matching issues.

**Comment by johnwcowan** [comment]
aphillips scripsit:

> If the context is the "find" portion of Charmod, then I think the
> recommendation is to ignore them always. If you're searching for "alone"
> and run into some "bodies" along the way, that may not be so bad.

I think that would be Very Bad Indeed, something like searching for
"its" and getting hits for "it's", or searching for ABC (Latin)
and getting ABC (Cyrillic).

## 

John Cowan          http://www.ccil.org/~cowan        cowan@ccil.org
Winter:  MIT, / Keio, INRIA, / Issue lots of Drafts.
So much more to understand! / Might simplicity return?
                (A "tanka", or extended haiku)

**Comment by aphillips** [comment]
@johnwcowan  That's possibly true, save that that people are frequently lazy or impeded in typing. There is a difference in perceived code points in the examples you use (even if, say, the Latin/Cyrillic pair look the same, they are neither the same code points nor the same perceived characters). Users would not expect to find Latin words typing Cyrillic letters, no matter what their shape.

I'll admit that I was being clever in my locution, but I was also careful to use the ZWNJ-free string as the search term. If you do a "find" on this page in your browser, typing "die" finds "bodies" and (unless you do something about matching case), typing "DIE" finds "bodies" too. Customers expect matches to be more permissive under certain circumstances (such as find) as compared to algorithmic access methods (where rigor is called for).

We also suggest elsewhere in the document that when users expend more effort on input that their input should be taken into account. If I type the ZWNJ (or VS or whatever) in as the "find" term, only strings actually containing ZWNJ et al should be found.

**Comment by johnwcowan** [comment]
aphillips scripsit:

> I'll admit that I was being clever in my locution, but I was also
> careful to use the ZWNJ-free string as the search term. If you do a
> "find" on this page in your browser, typing "die" finds "bodies" and
> (unless you do something about matching case), typing "DIE" finds
> "bodies" too. Customers expect matches to be more permissive under
> certain circumstances (such as find) as compared to algorithmic access
> methods (where rigor is called for).

Ah, I didn't understand that this was browser "find" as opposed to API's
for finding substrings.

## 

 John Cowan          http://www.ccil.org/~cowan        cowan@ccil.org
               Si hoc legere scis, nimium eruditionis habes.

**Comment by klensin** [comment]
In addition to the language-related issues noted, some other interesting examples have shown up in the context of various proposals to allow emoji in IDNs and elsewhere.  The Unicode emojii description, at least as I read it, restricts the use of ZWJ with emoji.  However it seems likely, given the very nature of emoji, that creativity will prevail over those restrictions (illustrated by a recent XKCD piece).  Since there are no applicable normalization  rules, even for ordering within a combining sequence, and that it is unclear whether, for a given emoji code point E, E ZWJ E is equivalent to E, adds emphasis, or describes/ illustrates something else entirely (lurid examples on request), the area is fraught with "opportunities" for confusion and positive and negative mismatches.

**Comment by aphillips** [comment]
@klensin Agreed. I'm not sure what to do about it, other than to point it out. Don't forget skin tone modifiers and variation selectors too.

Lacking normalization rules is only the tip of the proverbial emoji matching iceberg. The problem I have here is the classic editor's problem, though. I want to close this issue because I have addressed the "meaning" problem, particularly for Arabic and Indic scripts. I don't know what else to write. Suggest text?

**Comment by klensin** [comment]
--On Thursday, May 4, 2017 07:50 -0700 Addison Phillips
<notifications@github.com> wrote:

> @klensin Agreed. I'm not sure what to do about it, other than
> to point it out. Don't forget skin tone modifiers and
> variation selectors too.
> 
> Lacking normalization rules is only the tip of the proverbial
> emoji matching iceberg.

Yes.  I could have mentioned many others too, but the document
is about normalization, so I decided to resist the opportunity
to rant.   Similarly, the discussion was about ZWJ and ZWNJ, so
resisted the opportunity to engage with the skin tone issues and
that, AFAIK, those are the only code points or code point
sequences in Unicode whose meaning changes if rendered in
monochrome rather than color.

>  The problem I have here is the classic
> editor's problem, though. I want to close this issue because I
> have addressed the "meaning" problem, particularly for Arabic
> and Indic scripts. I don't know what else to write. Suggest
> text?

Staying narrowly to the topics charmod-norm is supposed to be
about, how about we say that, if emoji are treated as strings,
or part of strings, to be searched for or matched, some of the
same issues with ZWJ arise as do a variety of other issues,
[only] some of which are the result of the absence of
normalization conventions for symbol code points.  

I think that would let us move on.  My major concern was only
that the existing text appeared to ignore uses of ZWJ in strings
consisting of other than letters and that is a new problem and
set of issues since Charmod work started.

An alternate would be a new paragraph to the effect that, there
is reason to question the sanity, or at least the understanding,
of anyone who tries to organize a way to search for or match
emoji,  :-)

best,
    john

**Comment by aphillips** [comment]
> I could have mentioned many others too, but the document is about normalization, so I decided to resist the opportunity to rant.

No, the document is about string *matching* (but not searching, we hived that off). The short name is historical. Normalization is one technique of improving string matching.

I think the most we can say about emoji is: "garbage in, garbage out". String matching of emoji sequences depends on what the characters are. I suppose removing VS and skin tones makes sense for most matching cases, but reordering emojis in a ZWJ sequence is "above our pay grade" and, by definition, a decomposed family ZWJ sequence doesn't match the precomposed one. If one cares about such matching, the instruction is: "try to be consistent", just as it would be for a language such as Vietnamese (say) that has differently keyboarded sequences.

I will need to do an edit session. Let's see if I can wrangle all this into something.

**Comment by klensin** [comment]
Sorry... meant to say "the section is about normalization", not
"the document".  Otherwise, I think we are on the same page.

   john


--On Thursday, May 4, 2017 12:21 -0700 Addison Phillips
