### ISSUE TITLE
Removing meaning

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#85]
http://w3c.github.io/charmod-norm/#normalization_forms

"Normalization can remove meaning"

would it not be more accurate to say:

"Compatibility normalization can remove meaning"

**Comment by klensin** [comment]
I hope so but wouldn't count on canonical normalization never removing meaning,

**Comment by asmusf** [comment]
Since no conformant process is required to make a distinction between canonically equivalent forms it's more than foolish to rely on that distinction - especially in a distributed environment.

That said, there's no guarantee that absolutely everything will work the same. Any buffer-overrun bug might be triggered by a decomposed string, while the equivalent composed string passes fine. Just to give one example where neither intention nor conformance is involved.

For purposes of this document, the proposed change is appropriate and good.

**Comment by aphillips** [comment]
I made the change. It is the case that compatibility normalization nearly always removes some kind of "meaning". It could be argued that some canonical ones do as well, I suppose. Much of this information is supposed to be illustrative rather than exhaustive, which is why I wasn't more specific originally.

**Comment by r12a** [comment]
close ok by me
