### ISSUE TITLE
[ed] eliminating encoding variation

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#86]
http://w3c.github.io/charmod-norm/#normalizationLimitations

"who expect that Unicode Normalization will eliminate all encoding variation"

may be better to add:

"who expect that Unicode Normalization will eliminate all encoding variation for characters that appear the same visually."

actually, that's a repetition of the previosu sentence. So, maybe just end this sentence after "This is sometimes surprising to software developers and others."

**Comment by asmusf** [comment]
It's strictly speaking something like "encoded text elements". Otherwise you'd be working with two meanings of "character" which can get confusing. If you make it an example instead of a general statement, then you could use the word letter. However, let's step back a bit. Repeating the perv. sentence using different words is appropriate, because it emphasizes the point. The surprise is strongest when it comes to identifiers. So, let's use that case to emphasize the general statement. While we are at it, let's take out the two insertions  that clutter up the first sentence to streamline it.

"Applying a Unicode Normalization Form does not guarantee that two identical-looking strings always use the same underlying Unicode code points. This is sometimes surprising to software developers and others who expect that applying Unicode Normalization, will make sure that two different strings can never result in two identical-looking identifiers, for example. Normalization is, at best, only part of a string matching solution."

**Comment by aphillips** [comment]
I took a little of @asmusf 's comments and edited further. Here's the changed para:

> Applying a Unicode Normalization Form does not guarantee that two identical-looking normalized strings always use the same underlying Unicode code points. This includes the more-destructive KC and KD forms. This is sometimes surprising to software developers and others who expect that for strings, tokens, or identifiers to appear the same they must use the same underlying sequences. Normalization is, at best, only part of a string matching solution.

**Comment by r12a** [comment]
ok to close this for me
