### ISSUE TITLE
Limitations of Normalization - Confusion

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#88]
In addition to other issues covered by Rchard's notes,...

(1) "Homoglyph" is not a generally-recognized term.  Perhaps "called a homoglyph in Unicode documents" would be better.

(2) The so-called non-decomposable problem, i.e., characters that can be formed by combining sequences in which all of the code points involved that are associated with particular scripts are members of the same script as each other and of the composite character but that do not have decompositions to at least one such combining sequence, probably deserves mention.  AFAICT, UTC39 does not cover that set of cases, they can set a trap when users try to input characters ,of a script without quite the right keyboard, and they interact with language preferences in ways that I, at least, still don't fully understand.

(3) The paragraph starting "Similar examples of identical appearance..." at least needs an example or two, whether the above is incorporated or not.  As it is, it reads like hand-waving, especially for the cases UTS39 does not address.

(4) In the last paragraph, starting "Finally, note that Unicode Normalization, even..." you might want to note that some systems do equate these characters by add-on steps to Normalization.  IDNA2003 definitely did so.  I haven't checked whether UTR46 still does but doing so would be consistent with its apparent principle of preserving everything that "worked in" IDNA2003.

**Comment by asmusf** [comment]
(1) You can use Homograph, which covers cases where it's not a single "glyph". That term is a generic term simply meaning "written alike". It may not need the bold face, but it's a useful term to introduce.
(2) The more I look at it, I find the non-decomposable problem may be somewhat of a red herring. Latest example I have come across: in Khmer, the two sequences U+17D2 U+178F and U+17D2 U+178A display absolutely identically (while standalone the characters differ significantly in appearance). This is not covered by the non-decomposable issue, because these are not composed vs. decomposed sequences. And it occurs in the same language using the same keyboard. (Aside: my best guess is that some constraint in the language doesn't allow an actual minimal pair of two words being identical except for that sequence, so the writing system can get away with re-using a form, but when typing, people want to type the letter (DA or TA) that corresponds to the actual sound. For identifiers, this opens the door to spoofing, unless some steps are taken to prevent the use of a minimal pair.) 
(3) I agree. An example of a non decomposable, for example 08A1, the example I just gave, an example of a digraph and the example of Latin turned e (I think that's the name) would be good to map the nature of the problem.
(4) Besides additional transformation there are other steps that can be taken, depending on the protocols involved. Where identifiers are registered, the registration of one can be made to cause the other (homograph one) to be blocked from registration.

**Comment by aphillips** [comment]
(1) I have changed the term 'homoglyph' to 'homograph'.
(3) I have added most of the examples from @asmusf along with a bit more text
(4) Added a note to that effect, mentioning IDNA2003.

**Comment by r12a** [comment]
See https://github.com/w3c/charmod-norm/commit/c3d6ee795603532f018dbe38992e7e60fd9da6d2

**Comment by asmusf** [comment]
On 4/7/2016 1:26 AM, r12a wrote:

> See c3d6ee7 
> https://github.com/w3c/charmod-norm/commit/c3d6ee795603532f018dbe38992e7e60fd9da6d2
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/w3c/charmod-norm/issues/88#issuecomment-206757914
> 
> The latest edits include

```
old: Similar examples of identical appearance (called a
<dfn>homoglyph</dfn>)...
new: Other examples of similar or identical appearance examples of
identical appearance (called a <dfn>homograpph</dfn>)...
```

If you include "similar" on the same footing as "identical" then it 
would be better simply change homograph to "confusable".

We need some term to distinguish identical appearance from "if I hold it 
at arms length and squint" similarity, but if you do not make that 
distinction then the term "confusable" is the technical term to use. 
Then you can drop the scare quotes around the term in the next paragraph.

Also, the note on IDNA2003 may be overstating things by implicitly 
claiming that it successfully removes all distinctions mentioned. At the 
same time, it may understate the issue, because by its placement it 
appears a statement limited to characters with "same meaning or function".

I believe it would be more accurate to make this an independent 
paragraph and apply it more broadly to all efforts at overcoming 
limitations:

```
Note that some processes or protocols attempt to overcome these
limitations via the addition of add-on steps to the normalization
process. One example of this is IDNA2003.
```

(I'm still not sure about using IDNA2003 as an example. Seems backward 
looking to me, somehow).

**Comment by aphillips** [comment]
See 3188cd9

I attempted to address @asmusf 's comments by re-frying some of the text.

**Comment by r12a** [comment]
This section still seems odd to me.  It's under the Normalization section and it's called "Limitations of Normalization", but it's mostly about how visually similar items may have different underlying character compositions, of which normalization is just one example.  I'd be inclined to make 2.2.4 into 2.3 and give it a title more like "Matching confusable sequences", or some such.

**Comment by klensin** [comment]
FWIW, I agree with Richard about the oddity, which gets worse with each improvement we make to 2.2.4.  Not certain that making 2.2.4 into a new 2.3 is the right solution, but it would be good to do something.

**Comment by aphillips** [comment]
Okay, I can make a section on "Confusable Characters" out of it. 

I suspect some additional editorial tugging is needed to make sense out of Section 2 as a whole.

**Comment by aphillips** [comment]
@klensin @asmusf  See if you like the above commit [here](http://w3c.github.io/charmod-norm/#normalizationLimitations) and if it addresses this thread.

**Comment by klensin** [comment]
I like it, modulo one correction and one comment.

Correction: Please remove the reference to the DNS at the end.  First, "internationalized domain name system" is new terminology and could led to arguments about just what it means.  More important, while IDNA2003 attempted to make all small, roundish, sentence-terminators match the "dot" character that separates labels in domain names, one of the conclusions that led to IDNA2008 was that the attempt led to madness and could not be defined in a way that would be stable over time.  IDNA2008 is consequently written exclusively in terms of labels and makes no such association.

Comment: At the risk of digging up the bodies of dead wildebeest, I wish we could leave the notion of "confusable" as an apparent category of relationships out of this discussion.  "Identical" or "apparently identical" are fine, as are comments that people are easily confused and most of the discussion of similarity or apparent similarity among logical characters.    But we've seen claims that some rather extreme cases are confusable as well, e.g., "O" and "Q" (for someone unfamiliar with the script, the hook might be just decorative), "p" and "q" (perhaps it doesn't make a difference where the descender is located and perhaps U+006F U+0327 and/or U+006F U+0321  might be "the same as" at least one of those logical characters), and, absent context or in an unfamiliar context,  U+0602 might easily be mistaken for U+0055 in a sufficiently imaginative type style.

**Comment by aphillips** [comment]
@klensin I addressed your correction. I also attempted to address your comment by reducing (but not eliminating) the use of "confusable" as a term. I don't have a problem with saying "confusable" as a term per se, but I think you're right that referring to the appearance is what's important. 

I do make brief mention of the other "rather extreme cases" as:

> Other familiar if somewhat less "identical-looking" spoofs such as l vs. 1 or O and 0.

The point here is that things that look alike might not match each other and I think we've covered that :-)
